name: Check and Deploy to NPM

on:
  push:
    branches: 
      - deploy

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed packages
        id: set-matrix
        run: |
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            BASE_SHA=$(git rev-parse HEAD~1)
          else
            BASE_SHA=$(git hash-object -t tree /dev/null)
          fi
          
          HEAD_SHA=${{ github.sha }}
          
          echo "Comparing $BASE_SHA...$HEAD_SHA"
          
          PACKAGE_DIRS=$(find . -name "package.json" -not -path "*/node_modules/*" -not -path "./package.json" -exec dirname {} \; | sed 's/^\.\///')
          
          CHANGED_PACKAGES=()
          
          for dir in $PACKAGE_DIRS; do
            if git diff --quiet $BASE_SHA $HEAD_SHA -- "$dir"; then
              echo "No changes in $dir"
            else
              echo "Detected changes in $dir"
              # Only add first-level directories (no slashes in the path)
              if [[ "$dir" != *"/"* ]]; then
                CHANGED_PACKAGES+=("$dir")
              fi
            fi
          done
          
          if [ ${#CHANGED_PACKAGES[@]} -eq 0 ]; then
            echo "matrix={\"package\":[]}" >> $GITHUB_OUTPUT
            echo "No packages changed"
          else
            JSON_ARRAY=$(printf '"%s",' "${CHANGED_PACKAGES[@]}" | sed 's/,$//')
            echo "matrix={\"package\":[$JSON_ARRAY]}" >> $GITHUB_OUTPUT
            echo "Changed packages: ${CHANGED_PACKAGES[@]}"
          fi

  build-and-publish:
    needs: detect-changes
    if: ${{ github.event_name == 'push' && needs.detect-changes.outputs.matrix != '{"package":[]}' && github.ref == 'refs/heads/deploy' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: echo matrix
        run: echo "${{ toJson(matrix) }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.openjumper.cn'
      
      # - name: Install dependencies
      #   run: |
      #     cd ${{ matrix.package }}
      #     npm ci || npm install
      
      - name: Build package
        run: |
          cd ${{ matrix.package }}
          npm run build --if-present
      
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ matrix.package }}
          
          # 获取当前版本号
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Current version: $CURRENT_VERSION"
          
          # 检查当前版本是否已在 NPM registry 上发布
          if npm view $PACKAGE_NAME@$CURRENT_VERSION version &> /dev/null; then
            echo "版本 $CURRENT_VERSION 已存在，尝试取消发布..."
            npm unpublish $PACKAGE_NAME@$CURRENT_VERSION --force
          fi

          # 等待一段时间确保取消发布生效
          sleep 5
          
          # 发布
          npm publish --access public
  
  upload-changes-img:
    needs: detect-changes
    if: ${{ github.event_name == 'push' && needs.detect-changes.outputs.matrix != '{"package":[]}' && github.ref == 'refs/heads/deploy' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: echo matrix
        run: echo "${{ toJson(matrix) }}"
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHB_TOKEN }}
      
      - name: upload
        run: |
          cd ${{ matrix.package }}

          # 找到所有图片文件
          echo "找到以下PNG图片文件："
          find . -type f -name "*.png" -not -path "*/node_modules/*" -not -path "*/\.*/*"

          # 创建临时目录用于整理图片
          mkdir -p ../temp_images

          # 遍历所有PNG图片并保持相对路径结构复制到临时目录
          find . -type f -name "*.png" -not -path "*/node_modules/*" -not -path "*/\.*/*" | while read file; do
            filename=$(basename "$file")
            cp "$file" "../temp_images/$filename"
            echo "复制 $file 到 ../temp_images/$filename"
          done

          # 检查是否有找到图片
          if [ -z "$(ls -A ../temp_images)" ]; then
            echo "没有找到任何PNG图片"
            exit 0
          fi
      
      - name: 判断是否有图片需要上传
        run: |
          if [ -z "$(ls -A ../temp_images)" ]; then
            echo "没有找到任何PNG图片"
            exit 0
          fi

      - name: 使用SCP上传PNG图片
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "temp_images/*"
          target: "${{ secrets.IMG_TARGET }}"
          strip_components: 1
          rm: false
  
  # upload-all-img:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.GHB_TOKEN }}
      
  #     - name: 
  #       id: find_images
  #       run: |
  #         echo "找到以下PNG图片文件："
  #         find . -type f -name "*.png" -not -path "*/node_modules/*" -not -path "*/\.*/*"
          
  #         # 创建临时目录用于整理图片
  #         mkdir -p ./temp_images
          
  #         # 遍历所有PNG图片并保持相对路径结构复制到临时目录
  #         find . -type f -name "*.png" -not -path "*/node_modules/*" -not -path "*/\.*/*" | while read file; do
  #           filename=$(basename "$file")
  #           cp "$file" "./temp_images/$filename"
  #           echo "复制 $file 到 ./temp_images/$filename"
  #         done

  #         # 检查是否有找到图片
  #         if [ -z "$(ls -A ./temp_images)" ]; then
  #           echo "没有找到任何PNG图片"
  #           exit 0
  #         fi
      
  #     - name: 使用SCP上传PNG图片
  #       uses: appleboy/scp-action@v0.1.4
  #       with:
  #         host: ${{ secrets.SERVER }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         source: "temp_images/*"
  #         target: "${{ secrets.IMG_TARGET }}"
  #         strip_components: 1
  #         rm: false

  genJson-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.openjumper.cn'
      
      - name: Generate JSON
        run: node genjson.js
      
      - name: Check if JSON file exists
        run: |
          if [ -f "./boards.json" ]; then
            echo "File exists"
            cat ./boards.json | head -n 10
          else
            echo "File does not exist"
            ls -la
            exit 1
          fi
      
      - name: 使用 SCP 上传文件
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "boards.json"
          target: "${{ secrets.TARGET }}"
          timeout: 60s